{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_post_request[/store/order-./json_data/store_data.json-id-storage-200]", "rerun": "0"}, "1": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"I have a saved value for <container>\". Line 15 in scenario \"Using saved value in a later request\" in the feature \"C:\\Users\\Asus\\OneDrive\\Desktop\\automation\\PythonAutomation\\edited pytest-bdd\\pytest-bdd\\tests\\feature\\e2e_request.feature\"\n", "test_name": "test_using_saved_value_in_a_later_request", "rerun": "0"}}, "suite_name": "tests/steps/test_api_steps.py"}}}, "date": "March 07, 2023", "start_time": 1678172907.0335643, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}